export default {
    STATUS_BAR_SET_COLOR: '[STATUS_BAR] STATUS_BAR_SET_COLOR',
    STATUS_BAR_CLOSE: '[STATUS_BAR] STATUS_BAR_CLOSE',
    STATUS_BAR_OPEN: '[STATUS_BAR] STATUS_BAR_OPEN',
    STATUS_BAR_TOGGLE: '[STATUS_BAR] STATUS_BAR_TOGGLE',
};
