export default {
    TOP_PROGRESS_RESET: "[TOP_PROGRESS] TOP_PROGRESS_RESET",
    TOP_PROGRESS_UPDATE: "[TOP_PROGRESS] TOP_PROGRESS_UPDATE",
    TOP_PROGRESS_SHOW: "[TOP_PROGRESS] TOP_PROGRESS_SHOW",
    TOP_PROGRESS_HIDE: "[TOP_PROGRESS] TOP_PROGRESS_HIDE",
    TOP_PROGRESS_TOGGLE: "[TOP_PROGRESS] TOP_PROGRESS_TOGGLE",
}
